# Datetime
One of the most commonly used packages in Python which is extremely important is the <font color='goldenrod';>**datetime**</font> package. As mentioned previously, we will import the package the standard way and provide it with the alias of <font color='goldenrod';>**dt**</font>, please run the code in the cell below. The full documentation for the <font color='goldenrod';>**datetime**</font> package can be found below;

Link: https://docs.python.org/3/library/datetime.html

In [1]:
# provided code
import datetime as dt

The <font color='goldenrod';>**datetime**</font> package is what we will use for everything related to dates. This package supports 2 primary objects; the <font color='dodgerblue';>**date**</font> object which stores only Year, Month, and Day; as well as the <font color='crimson';>**datetime**</font> object, which is a full timestamp including hours, minutes, secons, and milliseconds.
The <font color='crimson';>**datetime**</font> object looks like the code below;
```python
# 2018-03-15 00:00:00 
a_timestamp = dt.datetime(2018,3,15)
```
and if we wanted to turn this into just a date, we would simply call the method ```.date()``` on our ```a_timestamp``` object.
```python
# 2018-03-15
a_date = a_timestamp.date()
```
<br>
## Datetime Object to String
We can also convert our <font color='goldenrod';>**datetime**</font> object to a string by using the ```.strftime()``` method. The formatting for how you want the <font color='goldenrod';>**datetime**</font> object to be converted to a string comes from this abbreviated table of available formatting options. All formatting options can be found in the link at the top of the page, about 2/3 the way down the website.
<table border="1" class="docutils">
<colgroup>
<col width="15%">
<col width="43%">
<col width="32%">
<col width="9%">
</colgroup>
<thead valign="bottom">
<tr class="row-odd"><th class="head">Directive</th>
<th class="head">Meaning</th>
<th class="head">Example</th>
<th class="head">Notes</th>
</tr>
</thead>
<tbody valign="top">
<tr class="row-even"><td><code class="docutils literal notranslate"><span class="pre">%a</span></code></td>
<td>Weekday as locale’s
abbreviated name.</td>
<td><div class="first last line-block">
<div class="line">Sun, Mon, …, Sat
(en_US);</div>
</div>
</td>
<td>(1)</td>
</tr>
<tr class="row-odd"><td><code class="docutils literal notranslate"><span class="pre">%A</span></code></td>
<td>Weekday as locale’s full name.</td>
<td><div class="first last line-block">
<div class="line">Sunday, Monday, …,
Saturday (en_US);</div>
</div>
</td>
<td>(1)</td>
</tr>
<tr class="row-even"><td><code class="docutils literal notranslate"><span class="pre">%w</span></code></td>
<td>Weekday as a decimal number,
where 0 is Sunday and 6 is
Saturday.</td>
<td>0, 1, …, 6</td>
<td>&nbsp;</td>
</tr>
<tr class="row-odd"><td><code class="docutils literal notranslate"><span class="pre">%d</span></code></td>
<td>Day of the month as a
zero-padded decimal number.</td>
<td>01, 02, …, 31</td>
<td>&nbsp;</td>
</tr>
<tr class="row-even"><td><code class="docutils literal notranslate"><span class="pre">%b</span></code></td>
<td>Month as locale’s abbreviated
name.</td>
<td><div class="first last line-block">
<div class="line">Jan, Feb, …, Dec
(en_US);</div>
</div>
</td>
<td>(1)</td>
</tr>
<tr class="row-odd"><td><code class="docutils literal notranslate"><span class="pre">%B</span></code></td>
<td>Month as locale’s full name.</td>
<td><div class="first last line-block">
<div class="line">January, February,
…, December (en_US);</div>
</div>
</td>
<td>(1)</td>
</tr>
<tr class="row-even"><td><code class="docutils literal notranslate"><span class="pre">%m</span></code></td>
<td>Month as a zero-padded
decimal number.</td>
<td>01, 02, …, 12</td>
<td>&nbsp;</td>
</tr>
<tr class="row-odd"><td><code class="docutils literal notranslate"><span class="pre">%y</span></code></td>
<td>Year without century as a
zero-padded decimal number.</td>
<td>00, 01, …, 99</td>
<td>&nbsp;</td>
</tr>
<tr class="row-even"><td><code class="docutils literal notranslate"><span class="pre">%Y</span></code></td>
<td>Year with century as a decimal
number.</td>
<td>0001, 0002, …, 2013,
2014, …, 9998, 9999</td>
<td>(2)</td>
</tr>
<tr class="row-odd"><td><code class="docutils literal notranslate"><span class="pre">%H</span></code></td>
<td>Hour (24-hour clock) as a
zero-padded decimal number.</td>
<td>00, 01, …, 23</td>
<td>&nbsp;</td>
</tr>
<tr class="row-even"><td><code class="docutils literal notranslate"><span class="pre">%I</span></code></td>
<td>Hour (12-hour clock) as a
zero-padded decimal number.</td>
<td>01, 02, …, 12</td>
<td>&nbsp;</td>
</tr>
<tr class="row-odd"><td><code class="docutils literal notranslate"><span class="pre">%p</span></code></td>
<td>Locale’s equivalent of either
AM or PM.</td>
<td><div class="first last line-block">
<div class="line">AM, PM (en_US);</div>
</div>
</td>
<td>(1),
(3)</td>
</tr>
<tr class="row-even"><td><code class="docutils literal notranslate"><span class="pre">%M</span></code></td>
<td>Minute as a zero-padded
decimal number.</td>
<td>00, 01, …, 59</td>
<td>&nbsp;</td>
</tr>
<tr class="row-odd"><td><code class="docutils literal notranslate"><span class="pre">%S</span></code></td>
<td>Second as a zero-padded
decimal number.</td>
<td>00, 01, …, 59</td>
<td>(4)</td>
</tr>
<tr class="row-even"><td><code class="docutils literal notranslate"><span class="pre">%f</span></code></td>
<td>Microsecond as a decimal
number, zero-padded on the
left.</td>
<td>000000, 000001, …,
999999</td>
<td>(5)</td>
</tr>
<tr class="row-odd"><td><code class="docutils literal notranslate"><span class="pre">%z</span></code></td>
<td>UTC offset in the form
±HHMM[SS[.ffffff]] (empty
string if the object is
naive).</td>
<td>(empty), +0000,
-0400, +1030,
+063415,
-030712.345216</td>
<td>(6)</td>
</tr>
<tr class="row-even"><td><code class="docutils literal notranslate"><span class="pre">%Z</span></code></td>
<td>Time zone name (empty string
if the object is naive).</td>
<td>(empty), UTC, EST, CST</td>
<td>&nbsp;</td>
</tr>
<tr class="row-odd"><td><code class="docutils literal notranslate"><span class="pre">%j</span></code></td>
<td>Day of the year as a
zero-padded decimal number.</td>
<td>001, 002, …, 366</td>
<td>&nbsp;</td>
</tr>
<tr class="row-even"><td><code class="docutils literal notranslate"><span class="pre">%U</span></code></td>
<td>Week number of the year
(Sunday as the first day of
the week) as a zero padded
decimal number. All days in a
new year preceding the first
Sunday are considered to be in
week 0.</td>
<td>00, 01, …, 53</td>
<td>(7)</td>
</tr>
<tr class="row-odd"><td><code class="docutils literal notranslate"><span class="pre">%W</span></code></td>
<td>Week number of the year
(Monday as the first day of
the week) as a decimal number.
All days in a new year
preceding the first Monday
are considered to be in
week 0.</td>
<td>00, 01, …, 53</td>
<td>(7)</td>
</tr>
<tr class="row-even"><td><code class="docutils literal notranslate"><span class="pre">%c</span></code></td>
<td>Locale’s appropriate date and
time representation.</td>
<td><div class="first last line-block">
<div class="line">Tue Aug 16 21:30:00
1988 (en_US);</div>
</div>
</td>
<td>(1)</td>
</tr>
<tr class="row-odd"><td><code class="docutils literal notranslate"><span class="pre">%x</span></code></td>
<td>Locale’s appropriate date
representation.</td>
<td><div class="first last line-block">
<div class="line">08/16/1988 (en_US);</div>
</div>
</td>
<td>(1)</td>
</tr>
<tr class="row-even"><td><code class="docutils literal notranslate"><span class="pre">%X</span></code></td>
<td>Locale’s appropriate time
representation.</td>
<td><div class="first last line-block">
<div class="line">21:30:00 (en_US);</div>
</div>
</td>
<td>(1)</td>
</tr>
<tr class="row-odd"><td><code class="docutils literal notranslate"><span class="pre">%%</span></code></td>
<td>A literal <code class="docutils literal notranslate"><span class="pre">'%'</span></code> character.</td>
<td>%</td>
<td>&nbsp;</td>
</tr>
</tbody>
</table>
<br>
We can use all of these terms inside of the ```.strftime()``` method to decide what string representation we want to use for our timestamp. The standard convention for timestamp to string conversion usually looks like this;

In [ ]:
# provided code
import datetime as dt
# a standard timestamp
a_timestamp = dt.datetime(2018,3,15,16,55,30)
print(a_timestamp)
# a string representation of a timestamp
a_timestamp_str = a_timestamp.strftime("%Y-%m-%d %H:%M:%S")
print(a_timestamp_str)

Note the difference in what is printed to the console. Depending on the data source some times we will have our timestamps in a String or in a <font color='goldenrod';>**datetime**</font> object format. Generally speaking, we will want to convert string <font color='goldenrod';>**datetime**</font> representations to actual <font color='goldenrod';>**datetime**</font> objects. The reason for this is that the <font color='goldenrod';>**datetime**</font> object has a few other really nice benefits to it which we will review. Before we go over the other functionality in the <font color='goldenrod';>**datetime**</font> package we will review how to convert a string representation of a timestamp into a <font color='goldenrod';>**datetime**</font> object.

<br>
## Datetime String to Datetime Object
We can also convert our <font color='goldenrod';>**datetime**</font> string to an object by using the ```.strptime()``` method. The same formatting applies to this method as we used with ```.strftime()```.
```python
import datetime as dt
# timestamp as a string
timestamp_str = "2018-03-27"
# converted to datetime object
timestamp = dt.datetime.strptime(timestamp_str, "%Y-%m-%d")
```
<br>
## Datetime Conversions Review
<br>
### When converting from Datetime Object to String
Use <font color='forestgreen';>**.strftime(string_format)**</font> method where ```string_format``` is something like ```"%Y-%m-%d"```
```python
import datetime as dt
# a standard timestamp
a_timestamp = dt.datetime(2018,3,15,16,55,30)
# a string representation of a timestamp
a_timestamp_str = a_timestamp.strftime("%Y-%m-%d %H:%M:%S")
```
<br>
### When converting from Datetime String to Object
Use <font color='forestgreen';>**datetime.strptime(datetime_object, string_format)**</font> method where ```string_format``` is something like ```"%Y-%m-%d"``` and ```datetime_object``` is a standard datetime object.
```python
import datetime as dt
# timestamp as a string
timestamp_str = "2018-03-27"
# converted to datetime object
timestamp = dt.datetime.strptime(timestamp_str, "%Y-%m-%d")
```

<br>
#### Exercise
Convert the following timestamp string representing March 27th in 2017 to datetime objects

In [ ]:
# your code goes here

# timestamp 1
ts1 = "2017-03-27"

# timestamp 2
ts2 = "03/27/2017"

# timestamp 3
ts3 = "2017-03-27 22:00"

## How about right now?
Do you need the current timestamp according to the computer you are on? Python and the <font color='goldenrod';>**datetime**</font> package can do this quickly and easily for you using the ```.now()``` method. See the example below.

In [ ]:
# provided code
import datetime as dt

right_now = dt.datetime.now()
print(right_now.strftime("%Y-%m-%d %H:%M:%S"))

## Accessing individual components of a Datetime object
The <font color='goldenrod';>**datetime**</font> object has a bunch of attributes to it so that you can garner additional information about the timestamp in question. Assume we have run the following line of code;
```python
timestamp = dt.datetime(2017,3,27,16,30,59)
```
<br>
### Year
If you needed just the year from the timestamp;
```python
# this would be 2017
timestamp.year
```
<br>
### Month
If you needed just the month from the timestamp;
```python
# this would be 3
timestamp.month
```
<br>
### Day
If you needed just the day from the timestamp;
```python
# this would be 27
timestamp.day
```
<br>
### Hour
If you needed just the hour from the timestamp;
```python
# this would be 16
timestamp.hour
```
<br>
### Minute
If you needed just the minute from the timestamp;
```python
# this would be 30
timestamp.minute
```
<br>
### Second
If you needed just the seconds from the timestamp;
```python
# this would be 59
timestamp.second
```
<br>
## What Day of the Week is this?
Python and the <font color='goldenrod';>**datetime**</font> package can also tell us what day of the week a particular date is using the ```.weekday()``` method. This method returns an integer where 0 is Monday and 6 is Sunday.
```python
timestamp = dt.datetime(2017,3,27,16,30,59)
# this turns out to be a Monday
this_equals_zero = timestamp.weekday()
```
<br>
## Operations on Datetime Objects (Timedelta)
We can increment (decrement) dates by a certain number of values using the <font color='orangered';>**timedelta**</font> object which is part of the <font color='goldenrod';>**datetime**</font> package. The <font color='orangered';>**timedelta**</font> object has the following structure;
<br><br>
**timedelta(days=0, seconds=0, microseconds=0, milliseconds=0, minutes=0, hours=0, weeks=0)**
<br><br>
Execute the code in the cell below and then we will start making some changes to that timestamp.

In [14]:
# provided code
import datetime as dt
ts = dt.datetime(2019,3,16)

Now what is the timestamp if we added 47 days to it? Not such an easy thing for a human to calculate on the fly but its incredible easy using Python.
```python
# datetime.datetime(2019, 5, 2, 0, 0)
ts + dt.timedelta(days=47)
```
#### Exercise
Try going back in time with our ```ts``` object we created before and go back 2 weeks and 4 days

In [ ]:
# your code goes here

When working with <font color='orangered';>**timedelta**</font> and <font color='goldenrod';>**datetime**</font> objects you can use the table below to understand, based on what operation you are doing, what kind of object you should expect to receive back.

<table border="1" class="docutils">
<colgroup>
<col width="55%">
<col width="45%">
</colgroup>
<thead valign="bottom">
<tr class="row-odd"><th class="head">Operation</th>
<th class="head">Result</th>
</tr>
</thead>
<tbody valign="top">
<tr class="row-even"><td><code class="docutils literal notranslate"><span class="pre">datetime2</span> <span class="pre">=</span> <span class="pre">datetime1</span> <span class="pre">+</span> <span class="pre">timedelta</span></code></td>
<td>(1)</td>
</tr>
<tr class="row-odd"><td><code class="docutils literal notranslate"><span class="pre">datetime2</span> <span class="pre">=</span> <span class="pre">datetime1</span> <span class="pre">-</span> <span class="pre">timedelta</span></code></td>
<td>(2)</td>
</tr>
<tr class="row-even"><td><code class="docutils literal notranslate"><span class="pre">timedelta</span> <span class="pre">=</span> <span class="pre">datetime1</span> <span class="pre">-</span> <span class="pre">datetime2</span></code></td>
<td>(3)</td>
</tr>
<tr class="row-odd"><td><code class="docutils literal notranslate"><span class="pre">datetime1</span> <span class="pre">&lt;</span> <span class="pre">datetime2</span></code></td>
<td>Compares <a class="reference internal" href="#datetime.datetime" title="datetime.datetime"><code class="xref py py-class docutils literal notranslate"><span class="pre">datetime</span></code></a> to
<a class="reference internal" href="#datetime.datetime" title="datetime.datetime"><code class="xref py py-class docutils literal notranslate"><span class="pre">datetime</span></code></a>. (4)</td>
</tr>
</tbody>
</table>
So for the example and exercise we just performed we would receive a <font color='goldenrod';>**datetime**</font> object back. When we want to know how much time has passed between two <font color='goldenrod';>**datetime**</font> objects we would receive back a <font color='orangered';>**timedelta**</font> object. I would argue that the <font color='orangered';>**timedelta**</font> object is one of the more confusing objects to work with in Python so I am going to dedicate a bit of work to putting up examples of working with this object. Execute the code below.

In [29]:
# provided code
# 430pm on 3/27/2018
ts1 = dt.datetime(2018,3,27,16,30)
# 7pm on 3/27/2017
ts2 = dt.datetime(2017,3,27,19)
# timedelta object
td = ts1 - ts2
print(td)

### How many days are between the two dates?
```python
td.days
```
<br>
### How many total seconds are between the two dates?
```python
td.total_seconds()
```
### How many minutes or hours?
So we know its been 364 days, but how many hours and minutes has it been in addition to the 364 days? This is where things get tricky. The <font color='orangered';>**timedelta**</font> object only has the following attributes; ```days```, ```seconds```, and ```microseconds```. The <font color='orangered';>**timedelta**</font> object also only has 1 method, which we called earlier, ```total_seconds()```.
<br>
To figure out how many hours have passed we need to do this;
```python
hours = td.seconds // 3600
```
Basically we are performing the following operation
1. How many minutes are in these seconds? This is equivalent to dividing the seconds by 60
2. Now that we know how many minutes we have, and 60 minutes makes one hour, we would need to divide the number of minutes by 60 to figure out how many hours
3. Hours can only be whole numbers though so we need to have an integer

```python
# method 1 of getting hours
hours = td.seconds // 3600
# method 2 of getting hours
mins = td.seconds / 60
hours_float = mins / 60
hours_int = int(hours_float)
# this will eval to True
hours_int == hours
```
<br>
To figure out how many minutes we need to do this;
```python
minutes = (td.seconds // 60) % 60
```
<br>
#### Exercise
Write a ```while``` loop which, after every 30 seconds, prints out the current timestamp. Once the timestamp has been printed 5 times, the ```while``` loop should exit.

In [ ]:
# your code goes here